http:
  port: 8085

apiEndpoints:
  public-auth:
    host: "*"
    paths:
      - "/api/auth/*"
    methods:
      - "POST"
      - "OPTIONS"
    secured: false

  secure-notes:
    host: "*"
    paths:
      - "/api/*"
    methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    secured: false

serviceEndpoints:
  notes-service:
    url: "http://secure-notes:5000"

policies:
  - cors
  - proxy

pipelines:
  auth:
    apiEndpoints:
      - public-auth
    policies:
      - cors:
          - action:
              origin:
                - "http://localhost:5173"
              methods:
                - "POST"
                - "OPTIONS"
              allowedHeaders:
                - "*"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: notes-service

  default:
    apiEndpoints:
      - secure-notes
    policies:
      - cors:
          - action:
              origin:
                - "http://localhost:5173"
              methods:
                - "GET"
                - "POST"
                - "PUT"
                - "PATCH"
                - "DELETE"
                - "OPTIONS"
              allowedHeaders:
                - "*"
              credentials: true
      - proxy:
          - action:
              serviceEndpoint: notes-service
